// This file was generated by script/gen_inlined.py
#include "lvgl.h"
#include "lv_themes/lv_theme_alien.h"
#include "lv_themes/lv_theme_mono.h"
#include "lv_themes/lv_theme_nemo.h"
#include "lv_themes/lv_theme_zen.h"
#include "lv_themes/lv_theme.h"
#include "lv_themes/lv_theme_night.h"
#include "lv_themes/lv_theme_material.h"
#include "lv_themes/lv_theme_default.h"
#include "lv_core/lv_vdb.h"
#include "lv_core/lv_obj.h"
#include "lv_core/lv_indev.h"
#include "lv_core/lv_group.h"
#include "lv_core/lv_refr.h"
#include "lv_core/lv_style.h"
#include "lv_misc/lv_ll.h"
#include "lv_misc/lv_task.h"
#include "lv_misc/lv_font.h"
#include "lv_misc/lv_circ.h"
#include "lv_misc/lv_color.h"
#include "lv_misc/lv_math.h"
#include "lv_misc/lv_ufs.h"
#include "lv_misc/lv_area.h"
#include "lv_misc/lv_txt.h"
#include "lv_misc/lv_log.h"
#include "lv_misc/lv_symbol_def.h"
#include "lv_misc/lv_mem.h"
#include "lv_misc/lv_anim.h"
#include "lv_misc/lv_fs.h"
#include "lv_objx/lv_gauge.h"
#include "lv_objx/lv_bar.h"
#include "lv_objx/lv_tabview.h"
#include "lv_objx/lv_imgbtn.h"
#include "lv_objx/lv_btn.h"
#include "lv_objx/lv_label.h"
#include "lv_objx/lv_mbox.h"
#include "lv_objx/lv_calendar.h"
#include "lv_objx/lv_preload.h"
#include "lv_objx/lv_slider.h"
#include "lv_objx/lv_led.h"
#include "lv_objx/lv_ddlist.h"
#include "lv_objx/lv_page.h"
#include "lv_objx/lv_btnm.h"
#include "lv_objx/lv_line.h"
#include "lv_objx/lv_kb.h"
#include "lv_objx/lv_lmeter.h"
#include "lv_objx/lv_sw.h"
#include "lv_objx/lv_win.h"
#include "lv_objx/lv_roller.h"
#include "lv_objx/lv_arc.h"
#include "lv_objx/lv_ta.h"
#include "lv_objx/lv_cont.h"
#include "lv_objx/lv_cb.h"
#include "lv_objx/lv_img.h"
#include "lv_objx/lv_chart.h"
#include "lv_objx/lv_list.h"
#include "lv_draw/lv_draw_rbasic.h"
#include "lv_draw/lv_draw_label.h"
#include "lv_draw/lv_draw_img.h"
#include "lv_draw/lv_draw_triangle.h"
#include "lv_draw/lv_draw_line.h"
#include "lv_draw/lv_draw_vbasic.h"
#include "lv_draw/lv_draw_rect.h"
#include "lv_draw/lv_draw.h"
#include "lv_draw/lv_draw_arc.h"
#include "lv_fonts/lv_font_builtin.h"
#include "lv_hal/lv_hal_disp.h"
#include "lv_hal/lv_hal_indev.h"
#include "lv_hal/lv_hal.h"
#include "lv_hal/lv_hal_tick.h"

uint8_t lv_color_to1_inline(lv_color_t color) {
    return lv_color_to1(color);
}
uint8_t lv_color_to8_inline(lv_color_t color) {
    return lv_color_to8(color);
}
uint16_t lv_color_to16_inline(lv_color_t color) {
    return lv_color_to16(color);
}
uint32_t lv_color_to32_inline(lv_color_t color) {
    return lv_color_to32(color);
}
lv_color_t lv_color_mix_inline(lv_color_t c1, lv_color_t c2, uint8_t mix) {
    return lv_color_mix(c1, c2, mix);
}
uint8_t lv_color_brightness_inline(lv_color_t color) {
    return lv_color_brightness(color);
}
void lv_area_copy_inline(lv_area_t *dest, const lv_area_t *src) {
    return lv_area_copy(dest, src);
}
lv_coord_t lv_area_get_width_inline(const lv_area_t *area_p) {
    return lv_area_get_width(area_p);
}
lv_coord_t lv_area_get_height_inline(const lv_area_t *area_p) {
    return lv_area_get_height(area_p);
}
uint8_t lv_font_get_height_inline(const lv_font_t *font_p) {
    return lv_font_get_height(font_p);
}
void lv_cont_set_style_inline(lv_obj_t *cont, lv_style_t *style) {
    return lv_cont_set_style(cont, style);
}
lv_style_t *lv_cont_get_style_inline(const lv_obj_t *cont) {
    return lv_cont_get_style(cont);
}
void lv_btn_set_layout_inline(lv_obj_t *btn, lv_layout_t layout) {
    return lv_btn_set_layout(btn, layout);
}
void lv_btn_set_fit_inline(lv_obj_t *btn, bool hor_en, bool ver_en) {
    return lv_btn_set_fit(btn, hor_en, ver_en);
}
lv_layout_t lv_btn_get_layout_inline(const lv_obj_t *btn) {
    return lv_btn_get_layout(btn);
}
bool lv_btn_get_hor_fit_inline(const lv_obj_t *btn) {
    return lv_btn_get_hor_fit(btn);
}
bool lv_btn_get_ver_fit_inline(const lv_obj_t *btn) {
    return lv_btn_get_ver_fit(btn);
}
void lv_imgbtn_set_toggle_inline(lv_obj_t *imgbtn, bool tgl) {
    return lv_imgbtn_set_toggle(imgbtn, tgl);
}
void lv_imgbtn_set_state_inline(lv_obj_t *imgbtn, lv_btn_state_t state) {
    return lv_imgbtn_set_state(imgbtn, state);
}
void lv_imgbtn_toggle_inline(lv_obj_t *imgbtn) {
    return lv_imgbtn_toggle(imgbtn);
}
void lv_imgbtn_set_action_inline(lv_obj_t *imgbtn, lv_btn_action_t type, lv_action_t action) {
    return lv_imgbtn_set_action(imgbtn, type, action);
}
lv_btn_state_t lv_imgbtn_get_state_inline(const lv_obj_t *imgbtn) {
    return lv_imgbtn_get_state(imgbtn);
}
bool lv_imgbtn_get_toggle_inline(const lv_obj_t *imgbtn) {
    return lv_imgbtn_get_toggle(imgbtn);
}
lv_action_t lv_imgbtn_get_action_inline(const lv_obj_t *imgbtn, lv_btn_action_t type) {
    return lv_imgbtn_get_action(imgbtn, type);
}
void lv_label_set_style_inline(lv_obj_t *label, lv_style_t *style) {
    return lv_label_set_style(label, style);
}
lv_style_t *lv_label_get_style_inline(const lv_obj_t *label) {
    return lv_label_get_style(label);
}
void lv_img_set_file_inline(lv_obj_t *img, const char *fn) {
    return lv_img_set_file(img, fn);
}
void lv_img_set_style_inline(lv_obj_t *img, lv_style_t *style) {
    return lv_img_set_style(img, style);
}
void lv_img_set_upscale_inline(lv_obj_t *img, bool upcale) {
    return lv_img_set_upscale(img, upcale);
}
lv_style_t *lv_img_get_style_inline(const lv_obj_t *img) {
    return lv_img_get_style(img);
}
bool lv_img_get_upscale_inline(const lv_obj_t *img) {
    return lv_img_get_upscale(img);
}
void lv_line_set_style_inline(lv_obj_t *line, lv_style_t *style) {
    return lv_line_set_style(line, style);
}
void lv_line_set_upscale_inline(lv_obj_t *line, bool upcale) {
    return lv_line_set_upscale(line, upcale);
}
lv_style_t *lv_line_get_style_inline(const lv_obj_t *line) {
    return lv_line_get_style(line);
}
bool lv_line_get_upscale_inline(const lv_obj_t *line) {
    return lv_line_get_upscale(line);
}
void lv_page_set_scrl_fit_inline(lv_obj_t *page, bool hor_en, bool ver_en) {
    return lv_page_set_scrl_fit(page, hor_en, ver_en);
}
void lv_page_set_scrl_width_inline(lv_obj_t *page, lv_coord_t w) {
    return lv_page_set_scrl_width(page, w);
}
void lv_page_set_scrl_height_inline(lv_obj_t *page, lv_coord_t h) {
    return lv_page_set_scrl_height(page, h);
}
void lv_page_set_scrl_layout_inline(lv_obj_t *page, lv_layout_t layout) {
    return lv_page_set_scrl_layout(page, layout);
}
lv_coord_t lv_page_get_scrl_width_inline(const lv_obj_t *page) {
    return lv_page_get_scrl_width(page);
}
lv_coord_t lv_page_get_scrl_height_inline(const lv_obj_t *page) {
    return lv_page_get_scrl_height(page);
}
lv_layout_t lv_page_get_scrl_layout_inline(const lv_obj_t *page) {
    return lv_page_get_scrl_layout(page);
}
bool lv_page_get_scrl_hor_fit_inline(const lv_obj_t *page) {
    return lv_page_get_scrl_hor_fit(page);
}
bool lv_page_get_scrl_fit_ver_inline(const lv_obj_t *page) {
    return lv_page_get_scrl_fit_ver(page);
}
void lv_list_set_sb_mode_inline(lv_obj_t *list, lv_sb_mode_t mode) {
    return lv_list_set_sb_mode(list, mode);
}
lv_sb_mode_t lv_list_get_sb_mode_inline(const lv_obj_t *list) {
    return lv_list_get_sb_mode(list);
}
void lv_chart_set_style_inline(lv_obj_t *chart, lv_style_t *style) {
    return lv_chart_set_style(chart, style);
}
lv_style_t *lv_chart_get_style_inline(const lv_obj_t *chart) {
    return lv_chart_get_style(chart);
}
void lv_cb_set_checked_inline(lv_obj_t *cb, bool checked) {
    return lv_cb_set_checked(cb, checked);
}
void lv_cb_set_inactive_inline(lv_obj_t *cb) {
    return lv_cb_set_inactive(cb);
}
void lv_cb_set_action_inline(lv_obj_t *cb, lv_action_t action) {
    return lv_cb_set_action(cb, action);
}
bool lv_cb_is_checked_inline(const lv_obj_t *cb) {
    return lv_cb_is_checked(cb);
}
lv_action_t lv_cb_get_action_inline(const lv_obj_t *cb) {
    return lv_cb_get_action(cb);
}
void lv_slider_set_value_inline(lv_obj_t *slider, int16_t value) {
    return lv_slider_set_value(slider, value);
}
void lv_slider_set_value_anim_inline(lv_obj_t *slider, int16_t value, uint16_t anim_time) {
    return lv_slider_set_value_anim(slider, value, anim_time);
}
void lv_slider_set_range_inline(lv_obj_t *slider, int16_t min, int16_t max) {
    return lv_slider_set_range(slider, min, max);
}
int16_t lv_slider_get_min_value_inline(const lv_obj_t *slider) {
    return lv_slider_get_min_value(slider);
}
int16_t lv_slider_get_max_value_inline(const lv_obj_t *slider) {
    return lv_slider_get_max_value(slider);
}
void lv_led_set_style_inline(lv_obj_t *led, lv_style_t *style) {
    return lv_led_set_style(led, style);
}
lv_style_t *lv_led_get_style_inline(const lv_obj_t *led) {
    return lv_led_get_style(led);
}
void lv_kb_set_map_inline(lv_obj_t *kb, const char **map) {
    return lv_kb_set_map(kb, map);
}
void lv_ddlist_set_sb_mode_inline(lv_obj_t *ddlist, lv_sb_mode_t mode) {
    return lv_ddlist_set_sb_mode(ddlist, mode);
}
lv_sb_mode_t lv_ddlist_get_sb_mode_inline(const lv_obj_t *ddlist) {
    return lv_ddlist_get_sb_mode(ddlist);
}
void lv_roller_set_options_inline(lv_obj_t *roller, const char *options) {
    return lv_roller_set_options(roller, options);
}
void lv_roller_set_action_inline(lv_obj_t *roller, lv_action_t action) {
    return lv_roller_set_action(roller, action);
}
void lv_roller_set_hor_fit_inline(lv_obj_t *roller, bool fit_en) {
    return lv_roller_set_hor_fit(roller, fit_en);
}
void lv_roller_set_anim_time_inline(lv_obj_t *roller, uint16_t anim_time) {
    return lv_roller_set_anim_time(roller, anim_time);
}
const char *lv_roller_get_options_inline(const lv_obj_t *roller) {
    return lv_roller_get_options(roller);
}
uint16_t lv_roller_get_selected_inline(const lv_obj_t *roller) {
    return lv_roller_get_selected(roller);
}
void lv_roller_get_selected_str_inline(const lv_obj_t *roller, char *buf) {
    return lv_roller_get_selected_str(roller, buf);
}
lv_action_t lv_roller_get_action_inline(const lv_obj_t *roller) {
    return lv_roller_get_action(roller);
}
uint16_t lv_roller_get_anim_time_inline(const lv_obj_t *roller) {
    return lv_roller_get_anim_time(roller);
}
void lv_ta_set_action_inline(lv_obj_t *ta, lv_action_t action) {
    return lv_ta_set_action(ta, action);
}
void lv_ta_set_sb_mode_inline(lv_obj_t *ta, lv_sb_mode_t mode) {
    return lv_ta_set_sb_mode(ta, mode);
}
lv_action_t lv_ta_get_action_inline(lv_obj_t *ta) {
    return lv_ta_get_action(ta);
}
lv_sb_mode_t lv_ta_get_sb_mode_inline(const lv_obj_t *ta) {
    return lv_ta_get_sb_mode(ta);
}
void lv_win_scroll_hor_inline(lv_obj_t *win, lv_coord_t dist) {
    return lv_win_scroll_hor(win, dist);
}
void lv_win_scroll_ver_inline(lv_obj_t *win, lv_coord_t dist) {
    return lv_win_scroll_ver(win, dist);
}
void lv_lmeter_set_style_inline(lv_obj_t *lmeter, lv_style_t *bg) {
    return lv_lmeter_set_style(lmeter, bg);
}
lv_style_t *lv_lmeter_get_style_inline(const lv_obj_t *lmeter) {
    return lv_lmeter_get_style(lmeter);
}
void lv_gauge_set_range_inline(lv_obj_t *gauge, int16_t min, int16_t max) {
    return lv_gauge_set_range(gauge, min, max);
}
void lv_gauge_set_critical_value_inline(lv_obj_t *gauge, int16_t value) {
    return lv_gauge_set_critical_value(gauge, value);
}
void lv_gauge_set_style_inline(lv_obj_t *gauge, lv_style_t *bg) {
    return lv_gauge_set_style(gauge, bg);
}
int16_t lv_gauge_get_min_value_inline(const lv_obj_t *lmeter) {
    return lv_gauge_get_min_value(lmeter);
}
int16_t lv_gauge_get_max_value_inline(const lv_obj_t *lmeter) {
    return lv_gauge_get_max_value(lmeter);
}
int16_t lv_gauge_get_critical_value_inline(const lv_obj_t *gauge) {
    return lv_gauge_get_critical_value(gauge);
}
uint8_t lv_gauge_get_line_count_inline(const lv_obj_t *gauge) {
    return lv_gauge_get_line_count(gauge);
}
uint16_t lv_gauge_get_scale_angle_inline(const lv_obj_t *gauge) {
    return lv_gauge_get_scale_angle(gauge);
}
lv_style_t *lv_gauge_get_style_inline(const lv_obj_t *gauge) {
    return lv_gauge_get_style(gauge);
}
void lv_sw_set_action_inline(lv_obj_t *sw, lv_action_t action) {
    return lv_sw_set_action(sw, action);
}
bool lv_sw_get_state_inline(const lv_obj_t *sw) {
    return lv_sw_get_state(sw);
}
lv_action_t lv_sw_get_action_inline(const lv_obj_t *slider) {
    return lv_sw_get_action(slider);
}
